Ecommerce_project/Ecommerce_app/urls.py
from django.urls import path
from . import views

app_name='Ecommerce_app'

urlpatterns=[
    path('', views.allprodcat, name='allprodcat'),
    path('<slug:c_slug>/', views.allprodcat, name='products_by_category'),
    path('<slug:cslug>/<slug:product_slug>/', views.prodetail, name='prodcatdetail'),

]

Ecommerce_project/cart/urls.py
from django.urls import path
from .import views


app_name='cart'

urlpatterns=[
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_cart_to_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove')
]

Ecommerce_project/Ecommerce_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250, unique=True)
    slug=models.SlugField(max_length=250, unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('Ecommerce_app:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name=models.CharField(max_length=250, unique=True)
    slug=models.SlugField(max_length=250, unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    avaviable=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('prodcatdetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

        def __str__(self):
            return '{}'.format(self.name)

Ecommerce_project/Ecommerce_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


def allprodcat(request, c_slug=None):
    c_page = None
    product_list: None

    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        product_list = Product.objects.all().filter(category=c_page, avaviable=True)
    else:
        product_list=Product.objects.all().filter(avaviable=True)

    paginator = Paginator(product_list, 6)

    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page=1
    try:
        products = paginator.page(page)
    except(EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'category': c_page, 'products': products})


def prodetail(request, cslug, product_slug):
    try:
        product = Product.objects.get(category__slug=cslug, slug=product_slug)
    except Product.DoesNotExist as e:
        raise e
    return render(request, 'product.html', {'Product': product})

Ecommerce_project/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from Ecommerce_app.models import Product
from .models import Cart, Cartitem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart


def add_to_cart(request, product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item=Cartitem.objects.get(Product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except Cartitem.DoesNotExist:
        cart_item=Cartitem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart=Cart.objects.filter(cart_id=_cart_id(request))
        cart_items=Cartitem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product, id=product_id)
    cart_item=Cartitem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cartitem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

Ecommerce_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/font.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/928bab6617.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div class="container">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

Ecommerce_project/templates/cart.html
{% extends 'base.html' %}
  {% load static %}
        {% block metadescription %}
            This is the cart page. proceed to review your items and place the order
        {% endblock %}
        {% block title %}
            Cart- ABC Company PVT LTD
        {% endblock %}
    {% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                    <h1 class="text-center my_title"> Your shopping Cart is empty</h1>
                <br>
                <p class="text-center"> Please click
                    <a href="{% url 'Ecommerce_app:allprodcat' %}">here</a> to continue shopping </p>
            </div>
        </div>

    {% else %}
        <div>
            <div class="text-center">
                <br>
                    <h1 class="text-center my_title"> Your shopping cart</h1>
                <br>
            </div>
        </div>

        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg6 text-center">
                <table class="table my_custom_table">

                    <thead class="my_custom_thread">
                        <tr>
                            <th colspan="5"> Your items </th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="cart_item.product.get_absolute_url">
                                        <img src="{{ cart_item.product.image.url }}" alt="" class="flat-left rounded custom-image">
                                    </a>
                                </td>
                                <td class="text-lef">
                                    {{ cart_item.product.name }}
                                    <br>
                                    SKV : {{ cart_item.product.id }}
                                    <br>
                                    price : {{ cart_item.product.price }}
                                    <br>
                                    QTY : {{ cart_item.quantity }} x $ {{ cart_item }}
                                </td>
                                <td>
                                    ${{ cart_item.sub_total }}
                                </td>
                                {% if cart_item.quantity < cart_item.prodct.stock %}
                                <td>
                                    <a href="{% url 'cart:add_to_cart' product_id=cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i> </a>
                                    &nbsp;
                                    <a href="{% url 'cart:cart_remove' cart_item.product.id  %}" class="custom_a"><i class="fa fa-minus custom_icon"></i> </a>
                                    &nbsp;
                                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i> </a>
                                </td>
                                {% else %}
                                <td>
                                    <a href="{% url 'cart:cart_remove' cart_item.product.id  %}" class="custom_a"><i class="fa fa-minus custom_icon"></i> </a>
                                    &nbsp;
                                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i> </a>
                                </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">

                    <table class="table my_custom_table">
                        <thead class="my_custom_thread">
                            <tr>
                                <th>Checkout</th>
                            </tr>
                        </thead>
                        <tbody>

                        <tr>
                            <td>Please review your shopping cart items before procceding with the order payment.</td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                your Total is :<strong>{{ total }}</strong>
                            </td>
                        </tr>
                        </tbody>
                    </table>

                    <div class="mx-auto">
                        <a href="{% url "Ecommerce_app:allprodcat" %}" class="btn btn-secondary btn-block my_custom_button"> Continue shopping </a>
                    </div>
                </div>
        </div>
    {% endif %}
{% endblock %}

Ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
    {% block metadescription %}
            {% if Category %}
                {{ Category.description | truncatewords:155 }}
            {% else %}
                Welcome to abc store where you can buy different items----
            {% endif %}
    {% endblock %}

    {% block title %}
        {% if Category %}
            {{ Category.name }}---ABC store
        {% else %}
            See our New collections ---@ABC store
        {% endif %}
    {% endblock %}

    {% block content %}
        {% if Category %}
            <div>
                <div class="row my_row_class">
                    <div class="ex-auto">
                    <p><a href="{% url 'Ecommerce_app:allprodcat' %}"> Our product collections</a> </p>
                    </div>
                </div>
            </div>
        {% endif %}
            <div class="ax-auto">
                {% if Category %}
                    <img class="my_image" src="{{ Category.image.url }}" alt="{{ Category.name }}" width="1200px" height="400px">
            </div>
                    <br>
                    <div>
                        <h1 class="text-center my_title">{{ Category.name }}</h1>
                        <p class="text-justify">{{ Category.description }}</p>
                    </div>
                {% else %}
                    <div>
                        <img class="my_image my_image_padding" src="{% static 'image/banner.png' %}" alt="Our products" width="1300px" height="400px">
                    </div>
                    <br>
                    <div>
                        <h1 class="text-center my_title">Fresh Fruits Online & Fresh Vegetables Online</h1>
                        <P class="text-justify">We’re not your average fruit importers. We have expertise in sourcing the choicest of fresh fruits from around the world and distributing it across the length and breadth of India. Our top-notch distribution network strengthened through almost a century of existence in the fruit business, works efficiently to ensure the fruits are delivered far and wide with an intriguing depth of freshness. We provide fresh fruits online and fresh vegetables online.

We have expertise in providing fresh fruits online and fresh vegetables online and offline and sourcing the choicest of fruits and vegetables from around the world</P>
                    </div>
                {% endif %}
            <div class="container">
                <div class="row max_auto">
                    {% for product in products.object_list %}
                        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                            <div class="card text-center " style="min-width: 18rem;" >
                                <a href="{{ product.category.get_url }}" > <img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}" ></a>
                                    <div class="card-body">
                                        <h4>{{ product.name }}</h4>
                                        <p>{{ product.price }}</p>
                                    </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
              <div class="mx-auto">
                  {% if products.paginator.num_pages > 1 %}

                      <hr>
                      <div class="text-center">
                      {% for pg in products.paginator.page_range %}
                          <a href="?page={{ pg }}" class="btn btn-light btn-sm {% if products.number == pg %} active{% endif %}">{{ pg }}</a>
                      {% endfor %}
                      </div>
                        <div class="text-center">
                            {% for p in products.paginator.page_range %}
                            {% endfor %}
                        </div>
                {% endif %}
              </div>
            </div>
    {% endblock %}

Ecommerce_project/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Ecommerce_app:allprodcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="{% url 'Ecommerce_app:allprodcat' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All products
          </a>

          <ul class="dropdown-menu">
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a></li>
              {% endfor %}
            <li><a class="dropdown-item" href="{% url 'Ecommerce_app:prodcatdetail' cslug='your_cslug_here' product_slug='your_product_slug_here' %}">Product detail</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}" >Your Cart()<i class="fa-solid fa-cart-shopping"></i>{{ item_count }}</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'search_app:searchresult' %}" method="get">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search<i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

Ecommerce_project/templates/product.html
{% extends 'base.html' %}
    {% load static %}
     {% block metadescription %}
        {{ product.description | truncatewords:155 }}
     {% endblock %}
    {% block title %}
        {% if Category %}
            {{ product.name }}--ABC Store
        {% endif %}
    {% endblock %}
    {% block content %}
        <div class="row my_prod_row_class">
            <div class="max_auto">
                <p><a href="{% url 'Ecommerce_app:allprodcat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a> | {{ product.name }} </p>
            </div>
        </div>
        <div class="container">
        <br>
         <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width: 18rem">
                    <a href="{{ product.get_absolute_url }}">  <img src="{{ product.image.url }}"   alt="{{ product.name }}" width="400px" height="400px"> </a>
                </div>
            </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6">

                        <h1 class="my_prod_title">{{ product.name }}</h1>
                        <p>${{ product.price }}</p>
                        <p class="my_title"><u>Product Description</u></p>
                        <p class="text-justify my_product_text">{{ product.description }}</p>
                        {% if product.stock <= 0 %}
                           <p class="text-justify my_product_text"><b>Out of stock</b></p>
                        {% else %}
                           <p><a class="btn-btn-secondary" href="{% url 'cart:add_cart_to_cart' product_id=product.id %}">Add to cart</a></p>
                        {% endif %}
                    </div>
                <div>
                </div>
        </div>
        </div>
    {% endblock %}